### ISSUE TITLE
create gui with resedit ?

### ISSUE THREAD

**Issue by ffred** [rodrigocfd/winsafe#1]
Hi,
when you say that "WinSafe works with both ordinary windows and resource dialogs", does it mean that it will be possible to use a tool like [ResEdit](http://www.resedit.net/) to create the GUI visually (or parts of it..)  with it's dialog editor and use the .rc file created ?

**Comment by rodrigocfd** [comment]
Exactly, you can, and it's **already** possible.

I'm testing with Visual Studio 2019 Resource Editor, but ResEdit does the same job.

Considering you have a dialog resource with an edit and a button, your code will look like this:

```rust
use winsafe::gui;

fn main() {
    let my_main = MyMain::new();
    if let Err(e) = my_main.dlg.run_main(None) {
        eprintln!("{}", e);
    }
}

#[derive(Clone)]
pub struct MyMain {
    dlg: gui::CustomMain,
    txt: gui::Edit,
    btn: gui::Button,

    Self { dlg, txt, btn }
}

impl MyMain {
    pub fn new() -> MyMain {
        // dialog ID = 102
        // icon ID = 101
        let dlg = gui::CustomMain::new_dlg(102, Some(101), None);

        // edit ID = 1001
        // button ID = 1002
        let txt = gui::Edit::new_dlg(&dlg, 1001);
        let btn = gui::Button::new_dlg(&dlg, 1002);

        let me = Self { dlg, txt, btn };
        me.events();
        me
    }
}
```

You're welcome to test it.

Actually I'm finishing an example to upload to the `examples` folder showing exactly that.

**Comment by ffred** [comment]
great thanks..
don't have much time actually to work with Rust, but will definitely test it soon.  :-)

**Comment by rodrigocfd** [comment]
No problem.

Feel free to open an issue if you need something.
