### ISSUE TITLE
nm_custom_draw should provide a mutable reference?

### ISSUE THREAD

**Issue by mattg23** [rodrigocfd/winsafe#106]
Hi!

Thanks for the great lib!
I am trying to change the colors for certain items in a list view.
So i used the `nm_custom_draw` event. 

This is my custom draw code:
```rust
        self.list_view.on().nm_custom_draw({            
            move |draw: &mut winsafe::NMLVCUSTOMDRAW| {
                match draw.mcd.dwDrawStage {
                    CDDS::PREPAINT => {
                        debug!("PREPAINT");
                        Ok(co::CDRF::NOTIFYITEMDRAW)
                    },
                    CDDS::ITEMPREPAINT => {
                        // set color here?
                        debug!("ITEMPREPAINT");

                        draw.clrText = COLORREF::new(255, 255, 255);
                        draw.clrTextBk = COLORREF::new(155, 0, 0);

                        Ok(co::CDRF::DODEFAULT)
                    }
                    _ => Ok(co::CDRF::DODEFAULT)
                }
            }
        });
```

In order to set the colors i needed to change the `nm_custom_draw` function to provide a `&mut NMLVCUSTOMDRAW`.

Original  `nm_custom_draw`:

```rust
	/// [`NM_CUSTOMDRAW`](https://learn.microsoft.com/en-us/windows/win32/controls/nm-customdraw-list-view)
	/// notification.
	pub fn nm_custom_draw<F>(&self, func: F)
		where F: Fn(&NMLVCUSTOMDRAW) -> AnyResult<co::CDRF> + 'static,
	{
		self.0.wm_notify(co::NM::CUSTOMDRAW,
			move |p| Ok(Some(func(unsafe { p.cast_nmhdr::<NMLVCUSTOMDRAW>() })?.raw() as _)));
	}
````

Changed:
```rust
	/// [`NM_CUSTOMDRAW`](https://learn.microsoft.com/en-us/windows/win32/controls/nm-customdraw-list-view)
	/// notification.
	pub fn nm_custom_draw<F>(&self, func: F)
		where F: FnMut(&mut NMLVCUSTOMDRAW) -> AnyResult<co::CDRF> + 'static,
	{
		self.0.wm_notify(co::NM::CUSTOMDRAW,
			move |p| Ok(Some(func(unsafe { p.cast_nmhdr_mut::<NMLVCUSTOMDRAW>() })?.raw() as _)));
	}
```

This works as expected:
![image](https://github.com/rodrigocfd/winsafe/assets/8948631/c00528a9-cf34-4913-a5b6-af0bc903fa08)

Question:
 - Am i missing something or should it be a mutable reference?
 - If it should be mutable i can offer a PR if you want (also for the other `nm_custom_draw` events of other controls).

**Comment by mattg23** [comment]
That was fast, thank you @rodrigocfd !

I can confirm, it works as expected.

One note: I needed to assign the colors this way:

```rust
let txt_clr = COLORREF::new(highlight.fg_color.0, highlight.fg_color.1, highlight.fg_color.2);
unsafe {
    *draw.clrText.as_mut() = txt_clr.raw();
}
```

If i do it any other way the compiler optimizes it away in release mode 🤷.

**Comment by rodrigocfd** [comment]
Won't this work for you?

```rust
self.lst_entries.on().nm_custom_draw(|p| {

	let blue = w::COLORREF::new(0x00, 0x00, 0xff);

	p.clrText = blue; // simple assignment!

	// ...

	Ok(co::CDRF::DODEFAULT)
});
```

**Comment by mattg23** [comment]
Unfortunately not.
I made a quick [repo reproducing the behavior](https://github.com/mattg23/win32_custom_draw_repro) if you want to try it out.
Do you have any ideas what is happening here? 

This is a learning project for me, so it's not a problem if i have to use unsafe.
But it would be nice to understand what exactly is going on here.

**Comment by rodrigocfd** [comment]
The root cause was way deeper than the message handling itself. The lambda parameter was originally const, then later cast to mutable, thus causing undefined behavior.This is a rule [that comes from C++](https://stackoverflow.com/a/11458071/6923555), which I fortunately already faced in my C++ days.

I still don't know how this change will propagate throughout all WM_NOTIFY events, but so far everything seems fine.

Your example is working for me with all profiles now. Let me know if it works for you.

**Comment by mattg23** [comment]
I've done some small testing with max optimizations enabled.
So far _everything works fine_. **Thank you** so much for the support!

Also thanks for the info. I checked your changes and the stackoverflow post you linked. 
This makes sense to me now.

I still have a bunch of features to implement, so i keep an eye out for anything suspicious.
