### ISSUE TITLE
How to change label text color?

### ISSUE THREAD

**Issue by GirkovArpa** [rodrigocfd/winsafe#11]
As you can see in the code below, `parms.hwnd` is always the handle to my label, because it's the only control on the window.  But the text is still black, not red as intended.  Is this a bug, just an unsupported feature, or am I doing something wrong?  

I've tried to translate what I've read on stackoverflow into the corresponding winsafe version.  The answers there say to return an `HBRUSH`, but the compiler says it must return an `HDC`, so I figured setting the brush of the `HDC` is equivalent.

```rust
self.wnd.on().wm_ctl_color_static({
  let self2 = self.clone();
  move |parms| {
    println!("{:?}", parms.hwnd == self2.lbl.hwnd()); // true
    let red = COLORREF::new(0xff, 0x00, 0x00);
    let brush = HBRUSH::CreateSolidBrush(red).unwrap();
    parms.hdc.SelectObjectBrush(brush);
    parms.hdc.SetTextColor(red).unwrap();
    parms.hdc.SetBkMode(winsafe::co::BKMODE::TRANSPARENT);
    parms.hdc
  }
});
```

**Comment by GirkovArpa** [comment]
Thanks!

![screenshot](https://i.imgur.com/nxhK9Gc.gif)

**Comment by rodrigocfd** [comment]
@GirkovArpa That's awesome, dude!
