### ISSUE TITLE
resizable_layout not work as expect

### ISSUE THREAD

**Issue by MDZZDYXCMDZZDYXC** [rodrigocfd/winsafe#114]
When I set the windows effect to "Don't show window contents when dragged", the variable layout didn't work as expected
![Uploading bug.gif…]()

**Comment by MDZZDYXCMDZZDYXC** [comment]
![bug](https://github.com/rodrigocfd/winsafe/assets/54584346/6f7338ab-f921-4aa8-9f52-1a412a11a658)

**Comment by MDZZDYXCMDZZDYXC** [comment]
`use winsafe::gui;
use winsafe::prelude::*;
fn main() {
    let window = gui::WindowMain::new_dlg(108, Some(128), None);
    let notresize = (gui::Horz::None,gui::Vert::None);
    let dsd = gui::Edit::new_dlg(&window, 1000, notresize);
    let btn = gui::Button::new_dlg(&window, 1002, (gui::Horz::Resize,gui::Vert::Resize));
    let tab = gui::ListView::new_dlg(&window, 1003, (gui::Horz::Repos,gui::Vert::Repos), Some(winsafe::HMENU::CreatePopupMenu().unwrap()));

    window.run_main(None);
    
}`

**Comment by MDZZDYXCMDZZDYXC** [comment]
[dataview.zip](https://github.com/rodrigocfd/winsafe/files/13777406/dataview.zip)

**Comment by rodrigocfd** [comment]
Try this:

```rust
fn main() {
	let window = gui::WindowMain::new_dlg(108, Some(128), None);

	use gui::{Horz as H, Vert as V};
	let dsd = gui::Edit::new_dlg(&window, 1000, (H::Resize, V::Repos));
	let btn = gui::Button::new_dlg(&window, 1002, (H::None, V::Repos));
	let tab = gui::ListView::new_dlg(&window, 1003, (H::Resize, V::Resize),
		Some(winsafe::HMENU::CreatePopupMenu().unwrap()));

	window.run_main(None);
}
```

There is a label which is not being handled (ID is 65535). In order to adjust it to the layout, you'll have to give it an ID and manage it through a [`Label`](https://rodrigocfd.github.io/winsafe/winsafe/gui/struct.Label.html).

**Comment by rodrigocfd** [comment]
I'll try to reproduce this here. Is this a system option? Where do I find it?

**Comment by MDZZDYXCMDZZDYXC** [comment]
Perhaps you can search "adjust the appearance and performance of Windows" in Settings.
But I found the path of the program as follows:
"C:\Windows\System32\SystemPropertiesPerformance.exe"
![image](https://github.com/rodrigocfd/winsafe/assets/54584346/305ea09a-4cf5-41fc-a94b-3373570bc5ca)

**Comment by rodrigocfd** [comment]
There was a very specific case where the LayoutArranger didn't fire on the 1st WM_SIZE call. Since hide contents while dragging only fires 1 event, the controls didn't resize at the first move.

Let me know if this fixes your problem.

**Comment by MDZZDYXCMDZZDYXC** [comment]
Thanks,it's works pretty well!
