### ISSUE TITLE
please  font  settings

### ISSUE THREAD

**Issue by Asm322** [rodrigocfd/winsafe#120]
Hi, please winsafe add an example with the font and its settings. Thank you.

**Comment by rodrigocfd** [comment]
Could you explain a bit further what you're trying to accomplish?

**Comment by Asm322** [comment]
hi, sorry for my English, I'm from Russia. I just started learning rust. I like your winsafe box, great. I want to write a simple program. I can do it. I can’t figure out how to change the font, size and how to work with it. thank you
--
Отправлено из Mail.ru для Android четверг, 14 марта 2024г., 02:51 +03:00 от Rodrigo  ***@***.*** :

**Comment by rodrigocfd** [comment]
How would you do it in C++?

**Comment by Asm322** [comment]
Thanks for the reply. I just started in programming. I started with Masm32, minimum C. I liked Rust and its concepts, after Masm32, memory management and errors with it are clear, your examples are clear to me. Sorry for the stupid questions. I understand the description on the Microsoft website. How to apply this in rust is not always clear. If you would make an example with the text, I would be very grateful to you.

**Comment by rodrigocfd** [comment]
Changing the font is done by creating a font, then sending a [`WM_SETFONT`](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-setfont) message.

WinSafe is just a thin layer over the Win32 API. If you learn how to do this in C (or C++), you can simply translate the code. Google around and you'll find plenty of examples.

**Comment by Asm322** [comment]
Hello. I'll ask one question, thank you. There are no problems with gui::Edit) But with wm_get_font, wm_set_font I can't figure out how to transfer and receive parameters I don't understand)))

**Comment by rodrigocfd** [comment]
Please see here:

* https://learn.microsoft.com/en-us/windows/win32/winmsg/about-messages-and-message-queues
