### ISSUE TITLE
Add missing API to open app in foreground?

### ISSUE THREAD

**Issue by binChris** [rodrigocfd/winsafe#121]
First of all, thanks for this lib, it is so much better to code against than the native Windows API!

I am trying to start and open an app in foreground and this needs functions currently not covered by winsafe:

- ShellExecuteEx - gives a chance to obtain the process handle
- WaitForInputIdle - so that the hwnd can be found via EnumWindows

Would it be ok to create a pull request for there functions? Plus struct  ShellExecuteEx internally, I think it's better to disect it in the public interface as its members are mixed input / output.

**Comment by rodrigocfd** [comment]
I pushed an implementation for [`WaitForInputIdle`](https://rodrigocfd.github.io/winsafe/winsafe/prelude/trait.user_Hprocess.html#method.WaitForInputIdle), which is not complicated.

`ShellExecuteEx`, however, will need some thought... it's fine to create a pull request, but it's often useful to brainstorm such APIs. Do you have anything in mind?

**Comment by binChris** [comment]
That's great, thanks for adding WaitForInputIdle!

I can understand you want to keep the winsafe API stable and avoid breaking changes. The original Windows API for ShellExecuteEx is quite horrible, mixing input/output fields in the same struct.

Let me think about this a little and we can discuss a possible API design here before making a PR.

**Comment by rodrigocfd** [comment]
Hi Chris,

I pushed an unsafe implementation of [`ShellExecuteEx`](https://rodrigocfd.github.io/winsafe/winsafe/fn.ShellExecuteEx.html) with a very bare-bones [`SHELLEXECUTEINFO`](https://rodrigocfd.github.io/winsafe/winsafe/struct.SHELLEXECUTEINFO.html). If we keep thinking about the *perfect* design, we probably would never finish it, the API is terrible.

So my idea is that, from this starting point, you try to write your stuff. Then we can discuss your pain points and make small improvements to `SHELLEXECUTEINFO`, until we reach a reasonable implementation.

If you find any difficulties, just reply down here and I'll be glad to help you.
