### ISSUE TITLE
Can't construct TRACKMOUSEEVENT

### ISSUE THREAD

**Issue by GirkovArpa** [rodrigocfd/winsafe#13]
Does winsafe support creating `TRACKMOUSEEVENT`?  

I get an error related to private fields.

```rust
let mut mouse_event = winsafe::TRACKMOUSEEVENT {
  dwFlags: winsafe::co::TME::HOVER | winsafe::co::TME::LEAVE,
  hwndTrack: self.lbl.hwnd(),
  dwHoverTime: 0,
  ..Default::default()
//^^^^^^^^^^^^^^^^^^^^ field `cbSize` is private
};
winsafe::TrackMouseEvent(&mut mouse_event);

let label_events = self.lbl.on_subclass();
label_events.wm_mouse_hover({
  move |params| {
    println!("{},{}", params.coords.x, params.coords.y);
  }
});
```

**Comment by GirkovArpa** [comment]
I edited my local clone of `winsafe` to make `cbSize` public:
```rust
#[repr(C)]
pub struct TRACKMOUSEEVENT {
	pub cbSize: u32,
	pub dwFlags: co::TME,
	pub hwndTrack: HWND,
	pub dwHoverTime: u32,
}
```
This prevented the error, but when I hover the label, the coords are not printed.

**Comment by rodrigocfd** [comment]
You can't use `..Default::default()` because there is at least 1 field which doesn't implement the `Default` trait. Most simple structs will work without problem, but more complex structs need to be initialized with `::default()` and then have its fields set:

```rust
let mut mouse_event = TRACKMOUSEEVENT::default();
mouse_event.dwFlags = co::TME::HOVER | co::TME::LEAVE;
mouse_event.hwndTrack = self.lbl.hwnd();
mouse_event.dwHoverTime = 0;
```

This design is intentional. It makes it impossible to have the struct without its `cbSize` initialized. Also, there are more extreme cases like [`TASKDIALOGCONFIG`](https://rodrigocfd.github.io/winsafe/winsafe/struct.TASKDIALOGCONFIG.html) – which has mixed fields and two unions, a [total nightmare!](https://docs.microsoft.com/en-us/windows/win32/api/commctrl/ns-commctrl-taskdialogconfig) – where you can't even set the fields directly: you need to use getter and setter methods. All that stuff is needed to keep the struct "safe", in a valid state, which is idiomatic Rust.

As for the mouse tracking thing, see if [this example](https://docs.microsoft.com/en-us/windows/win32/learnwin32/other-mouse-operations#mouse-tracking-events-hover-and-leave) helps you.

**Comment by GirkovArpa** [comment]
I see.  My limited knowledge of Rust was the issue then.

I did check out that example, and it suggests the following code should print `"Hovering!"` the first time the cursor enters the window, and then stop (until `TRACKMOUSEEVENT` is called again).  

But, nothing happens.

Why?

```rust
self.wnd.on().wm_create({
  let self2 = self.clone(); 
  move |_| {
    let mut mouse_event = TRACKMOUSEEVENT::default();
    mouse_event.dwFlags = co::TME::HOVER | co::TME::LEAVE;
    mouse_event.hwndTrack = self2.wnd.hwnd();
    mouse_event.dwHoverTime = 0;
    winsafe::TrackMouseEvent(&mut mouse_event);
    1
  }
});

self.wnd.on().wm_mouse_hover({
  move |_| {
    println!("Hovering!");
  }
});
```

**Comment by rodrigocfd** [comment]
Your code is different from the example. The tracking should start in `wm_mouse_move`, and end in `wm_mouse_leave` and `wm_mouse_hover`.

I didn't test the example, but since it's from the official docs, I assume it's correct.

**Comment by GirkovArpa** [comment]
Here is my attempt as replicating that example.

It doesn't work for the label (nothing is printed), using the current `winsafe` respository.

But it does work for the window, if `let label_events = self.lbl.on_subclass();` is erased and all occurences of `label_events` is replaced with `self.wnd.on()`.

```rust
use lazy_static::lazy_static;
use std::sync::Mutex;
use winsafe::{co::TME, gui, TrackMouseEvent, TRACKMOUSEEVENT};

const HOVER_DEFAULT: u32 = 400;

lazy_static! {
    static ref TRACKING: Mutex<bool> = Mutex::new(false);
}

fn main() {
    let my = MyWindow::new();
    my.wnd.run_main(None).unwrap();
}

#[derive(Clone)]
pub struct MyWindow {
    wnd: gui::WindowMain,
    lbl: gui::Label,
}

impl MyWindow {
    pub fn new() -> MyWindow {
        let wnd = gui::WindowMain::new(gui::WindowMainOpts {
            ..Default::default()
        });

        let lbl = gui::Label::new(
            &wnd,
            gui::LabelOpts {
                text: "Hover me!".to_string(),
                ..Default::default()
            },
        );

        let new_self = Self { wnd, lbl };

        new_self.events();
        new_self
    }

    fn track(&self) -> () {
        *TRACKING.lock().unwrap() = true;
    }

    fn reset(&self) -> () {
        *TRACKING.lock().unwrap() = false;
    }

    fn events(&self) {
        let label_events = self.lbl.on_subclass();

        label_events.wm_mouse_move({
            let self2 = self.clone();
            move |_| {
                if !*TRACKING.lock().unwrap() {
                    let mut mouse_event = TRACKMOUSEEVENT::default();
                    mouse_event.dwFlags = TME::HOVER | TME::LEAVE;
                    mouse_event.hwndTrack = self2.wnd.hwnd();
                    mouse_event.dwHoverTime = HOVER_DEFAULT;
                    TrackMouseEvent(&mut mouse_event).unwrap();
                    self2.track();
                }
            }
        });

        label_events.wm_mouse_leave({
            let self2 = self.clone();
            move || {
                println!("Left!");
                self2.reset();
            }
        });

        label_events.wm_mouse_hover({
            let self2 = self.clone();
            move |_| {
                println!("Hovering!");
                self2.reset();
            }
        });
    }
}
```

**Comment by rodrigocfd** [comment]
Your code is still different from the example. The tracking should start in `wm_mouse_move`, and end in `wm_mouse_leave` and `wm_mouse_hover`.

I'm currently on vacation and away from my computer. I'll be back next week, then I'll try to translate the code from C++ to Rust.

**Comment by rodrigocfd** [comment]
Check this out...

```rust
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use winsafe::{self as w, co, gui};

fn main() {
	let my = MyWindow::new();
	if let Err(e) = my.wnd.run_main(None) {
		eprintln!("{}", e);
	}
}

#[derive(Clone)]
pub struct MyWindow {
	wnd: gui::WindowMain,
	lbl: gui::Label,
}

impl MyWindow {
	pub fn new() -> Self {
		let wnd = gui::WindowMain::new(
			gui::WindowMainOpts {
				class_bg_brush: w::HBRUSH::from_sys_color(co::COLOR::WINDOW),
				..Default::default()
			},
		);

		let lbl = gui::Label::new(
			&wnd,
			gui::LabelOpts {
				text: "Hover me!".to_owned(),
				position: w::POINT::new(50, 50),
				..Default::default()
			},
		);

		let new_self = Self { wnd, lbl };
		new_self.events();
		new_self
	}

	fn events(&self) {
		self.lbl.on_subclass().wm_mouse_move({
			let self2 = self.clone();
			move |p| {
				println!("Hovering {} {}", p.coords.x, p.coords.x);
			}
		});
	}
}

```

**Comment by GirkovArpa** [comment]
I know it's been awhile, but thank you!  I just tested it and it works perfectly.
