### ISSUE TITLE
ERROR(0x0078 120) This function is not supported on this system.

### ISSUE THREAD

**Issue by CodecNomad** [rodrigocfd/winsafe#132]
Example:
```
let mouse_input = MOUSEINPUT {
      dx: -relative_location.0 as i32,
      dy: -relative_location.1 as i32,
      mouseData: 0,
      dwFlags: MOUSEEVENTF::MOVE,
      time: 0,
      dwExtraInfo: 0,
  };

  match SendInput(&[HwKbMouse::Mouse(mouse_input)]) {
      Ok(_) => println!("Mouse input sent successfully"),
      Err(err) => eprintln!("Error sending mouse input: {:?}", err),
  }
```
I'm on windows 11 22h2. I can sendinput using winapi in c++. Why exactly is the function unsupported on my system?

**Comment by rodrigocfd** [comment]
Since `SendInput` is a rather old Win32 function, it's unlikely to be the one. The problem must be somewhere else in your code.

**Comment by CodecNomad** [comment]
I don't have that error handler anywhere else

**Comment by rodrigocfd** [comment]
You actually found a bug: the internal `dwType` field of the `INPUT` struct was not being set. The returned error is very deceiving though: the method **is** supported, but the given data combination is not. So Windows should instead return something like "invalid arguments".

Anyway... I fixed it. Let me know if it's working now.

(Until a new version is published, you can use it right away by [pointing directly to GitHub](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories).)

**Comment by CodecNomad** [comment]
Alright, thanks

**Comment by tneum-celonis** [comment]
Can you link the PR or commit related to the fix here for traceability? Might be helpful to people who find this in the future

**Comment by rodrigocfd** [comment]
> @rodrigocfd Can you link the PR or commit related to the fix here for traceability? Might be helpful for people who find this in the future

It is...
