### ISSUE TITLE
Never sets `class name` correctly for window

### ISSUE THREAD

**Issue by yu-d** [rodrigocfd/winsafe#134]
I encountered an issue while using the `01_button_click` example. The class name is not being set correctly.

Upon tracking the code, I found that the problem is around [raw_main.rs#L57](https://github.com/rodrigocfd/winsafe/blob/bf9fba5b6aa237cbe0c7ca863603388bea2240e3/src/gui/windows/raw_main.rs#L57). Although options with a class name are accepted, they are never used. The class name is always set to the default value as seen in [raw_base.rs#L68](https://github.com/rodrigocfd/winsafe/blob/bf9fba5b6aa237cbe0c7ca863603388bea2240e3/src/gui/windows/raw_base.rs#L68).

Could you please take a look at this issue?

Thank you for your assistance.

**Comment by rodrigocfd** [comment]
Oh I completely overlooked that.

Let me know if it works for you now.
