### ISSUE TITLE
[Question]  How do I send mouse and key events

### ISSUE THREAD

**Issue by LambdaMan2K** [rodrigocfd/winsafe#14]
Hey, thank you for working on this project, its great !.  
I am playing around with winapi in general for learning, so what is the correct way to send mouse and key events to a window since I could use this in a work project for automation of an app at work , it is already in production but I used global key events so this would be better using direct msg .

I wonder if this should work, cuz it doss not seem to work for me no right click happens,
and the FindWindow function should not not have the class name as an Optional?
and is the xy cords relative to the window or the screen? Thank you  :)
rs```
 let hwnd = HWND::FindWindow("Notepad", "Untitled - Notepad")?;
    hwnd.SetForegroundWindow();
    hwnd.SetFocus();
    let m = wm::RButtonDown {
        vkey_code: co::VK::RBUTTON,
        coords: POINT { x: 8, y: 8 },
    };
    hwnd.SendMessage(m);
```

**Comment by rodrigocfd** [comment]
Hi,

Thank you, I'm glad it works for you.

You are correct about the `FindWindow`, I just [fixed it](https://rodrigocfd.github.io/winsafe/winsafe/struct.HWND.html#method.FindWindow). It will be published on the next version, but you can use it right now by cloning the repo and using it [as a local dependency](https://stackoverflow.com/a/33025972/6923555).

As for the right-click automation, I think it's a bit more complicated than that. I never wrote anything like this, but it seems that you have to send both a `WM_KEYDOWN` and a `WM_KEYUP`, [as shown here](https://stackoverflow.com/q/46306860/6923555).

**Comment by LambdaMan2K** [comment]
super, it is fine i just did the mouse events using winapi :) you can just close this thanks

**Comment by rodrigocfd** [comment]
That was the idea since the beginning: be able to use any C++ Win32 tutorial (they are abundant) with idiomatic Rust.

I'm glad it worked for you. Have fun.
