### ISSUE TITLE
How about `GetModuleHandleExW`?

### ISSUE THREAD

**Issue by justanotheranonymoususer** [rodrigocfd/winsafe#141]
This is a really nifty crate, kudos!

How about being able to implement something like this without unsafe:

https://github.com/rust-lang/rust/blob/279604832887abeaea0cb31c20590c43dea497ae/compiler/rustc_session/src/filesearch.rs#L119-L152

**Comment by rodrigocfd** [comment]
Does this work for you?

```rust
use winsafe::{self as w, prelude::*, co};

fn main() {
	let file_name = current_dll_path().unwrap();
	println!("{file_name}");
}

fn current_dll_path() -> w::AnyResult<String> {
	let module = w::HINSTANCE::GetModuleHandleEx(
		w::AddrStr::Addr(current_dll_path as _),
		co::GET_MODULE_HANDLE_EX_FLAG::NoValue,
	)?;

	let file_name = module.GetModuleFileName()?;

	Ok(file_name)
}
```

**Comment by justanotheranonymoususer** [comment]
Yes, looks good, thanks

```
	///
	/// The `GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT` flag is never used,
	/// for safety reasons.
```

I assume you could return enum, return whatever GetModuleHandle returns in that case? And also handle pinning better, as no FreeLibrary needed in that case?

**Comment by rodrigocfd** [comment]
> I assume you could return enum, return whatever GetModuleHandle returns in that case? And also handle pinning better, as no FreeLibrary needed in that case?

Can you write me a sketch of your suggestion?

**Comment by justanotheranonymoususer** [comment]
I can't rn, on mobile, but an enum of:

SysResult<HINSTANCE> (if not bumped count) 

SysResult<FreeLibraryGuard> (if bumped by one) 

And if pinned, not sure, maybe same as not bumped?

**Comment by rodrigocfd** [comment]
I don't really like the idea of returning an enum:

```rust
let hmodule = match GetModuleHandleEx(FLAG_REFCOUNTED) {
    Counted(hmodule) => hmodule,
    NotCounted(_) => panic!("This never happens!"),
};
```

The problem with the C version is that you must remember calling `FreeLibrary` afterwards, and the non-refcounted flag alleviates this burden. In my implementation, you receive a guard, which will always call `FreeLibrary` for you.

But maybe I don't know some corner case... do you have an actual use case for the non-refcounted version?
