### ISSUE TITLE
cargo fmt, maybe?

### ISSUE THREAD

**Issue by y15un** [rodrigocfd/winsafe#18]
currently this repo indents with tabs, but the [style guide](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md#indentation-and-line-width) recommends to use spaces (4, specifically).

this bugged me greatly because by default vscode with rust extension will do 'format document' automatically upon every save, and it tries to convert all the indenting tabs to spaces.

there are two options i'd like to recommend:
1. switch to spaces: doing a `cargo fmt` run to get a sane-enough outcome now
   * warning: this will create a massive commit, but better do this now than later i guess?
2. keep using tabs: have a [`rustfmt.toml`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md) added to the repo with `hard_tabs` set to `true`
   * this will at least prevent vscode trying to auto-reformat document on every save.

just my two cents!

**Comment by rodrigocfd** [comment]
I give rustfmt a shot from time to time, and currently I still disagree very much with its formatting decisions, even when extensively tweaking `rustfmt.toml`. The `hard_tabs = true` option is always my first tweak – I'm a barbarian who likes 3 spaces, so with tabs everyone can set the width they want, and so can myself.

I'm a _huge_ fan of gofmt, and I'm really looking forward to use rustfmt one day. But it's not really there yet.

Thank you for your concern, be sure I'll keep an eye on rustfmt.
