### ISSUE TITLE
`msg::wm::Char` has its character code in `u32` so by default incompatible with `co::VK` (which expects `u16`)

### ISSUE THREAD

**Issue by y15un** [rodrigocfd/winsafe#19]
would it be safe to cast `Char::char_code` as `u16`?

basically i'm thinking of:
```rust
use winsafe::{
    co::VK,
    msg::wm::Char,
    prelude::*
};

ctl_edit.on_subclass().wm_char({
    move |char_info: Char| -> ErrResult<()> {
        if VK::from(char_info.char_code as u16) == VK::RETURN { // u16 casting safe??
            // user pressed enter inside this edit control
        }
        todo!() // TODO: fill in
    }
});
```

**Comment by rodrigocfd** [comment]
I asked myself this when I was implementing this message. The `WM_CHAR` parameter set is shared with other messages, like `WM_KEYDOWN`, and although it's officially listed as `u32`, it is indeed an `u16`. This seems to fit all messages to where it belongs.

So, until I see something odd, I'll take your advice and change it from `u32` to `u16`.
