### ISSUE TITLE
Adding a safe wrapper around ChangeDisplaySettingsExW

### ISSUE THREAD

**Issue by amithkk** [rodrigocfd/winsafe#20]
Currently, this crate only has a wrapper around [ChangeDisplaySettingsW](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-changedisplaysettingsw), which is limited to changing device settings for the "Default" or primary display. However this crate already provides [EnumDisplaySettingsExW](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumdisplaysettingsexw) that allows you to retrieve the DEVMODE struct for any display

This issue proposes adding [ChangeDisplaySettingsExW](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-changedisplaysettingsexw) which takes in a parameter to specify the device name so that one can both read and write device settings  for all displays

**Comment by michidk** [comment]
Tested your branch and works great! Is there anything blocking this from getting merged?

**Comment by rodrigocfd** [comment]
Merged https://github.com/rodrigocfd/winsafe/pull/21.
