### ISSUE TITLE
DispatchMessage, SendMessage, DefWindowProc, and PostThreadMessage are all unsound.

### ISSUE THREAD

**Issue by MaulingMonkey** [rodrigocfd/winsafe#24]
Sending window messages in general should be `unsafe`.  `DispatchMessage` - among others - is not.

https://github.com/rodrigocfd/winsafe/blob/06b1c08f4180e3af4fe683ef972f1f488b6aa735/src/user/funcs.rs#L100-L103

While the underlying DispatchMessage does a lot of parameter checking - including forbidding most system messages that interpret wparam/lparam as pointers by returning `ERROR_MESSAGE_SYNC_ONLY` - it cannot do the same for WM_USER+n or WM_APP+n messages which might interpret wparam/lparam as pointers.

For example, Microsoft's own `TOOLBARCLASSNAME` (`"ToolbarWindow32"`) expects `wparam` to be a pointer to an array for [TB_ADDBUTTONSW](https://docs.microsoft.com/en-us/windows/win32/controls/tb-addbuttons) (WM_USER+68).  While the docs recommend using SendMessage, DispatchMessage also works, and can crash / access violation if fed an invalid pointer.  Other messages could even *mutate* what's pointed to, causing random memory corruption instead of a nice and clean access violation.

This means that if any middleware, library, injected DLL, etc. might *ever* create a window containing a toolbar on one of your threads, you can use DispatchMessage to cause undefined behavior.

---

SendMessage and DefWindowProc have similar issues, although there are traits involved muddying things up.  Additionally, SendMessage won't reject messages with ERROR_MESSAGE_SYNC_ONLY to my knowledge.  The traits involved are "safe" - it appears you're able to implement them to use e.g. [WM::SETTEXT](https://docs.rs/winsafe/latest/winsafe/co/struct.WM.html#associatedconstant.SETTEXT) without any `unsafe`, despite the possibility of passing an invalid pointer in wparam for the string text.

PostThreadMessage at least won't dispatch to a wndproc... but I promise you that third parties *will* inject threads into your process (game overlays, debuggers, ...), and will treat wparam/lparam as pointers for some WM_USER+N messages.

**Comment by rodrigocfd** [comment]
I agree about `DispatchMessage`. The fact it carries a `MSG` – which can carry any kind of wild pointer – can be interpreted as unsoundness. Although I've never seen anyone using it instead of `SendMessage`, nothing forbids you from doing this.

The [`SendMessage`](https://rodrigocfd.github.io/winsafe/winsafe/prelude/trait.UserHwnd.html#method.SendMessage) itself and similar ones, however, appear fine to me with the [`MsgSend`](https://rodrigocfd.github.io/winsafe/winsafe/prelude/trait.MsgSend.html) trait bound – which gave me a _hard time_ implementing, since I had to go through *all* the messages one by one, understand what they do, and then write the specific struct to *each one* of them.

**Comment by rodrigocfd** [comment]
Feel free to reopen the issue if you discuss it.

**Comment by MaulingMonkey** [comment]
Thing is, MsgSend isn't sealed - anyone can implement it from any crate - and can implement it incorrectly and unsoundly, without a lick of `unsafe`:

```rust
pub struct UnsoundMessageExample;

impl MsgSend for UnsoundMessageExample {
    type RetType = isize;
    fn convert_ret(&self, v: isize) -> Self::RetType { v }
    fn as_generic_wm(&mut self) -> WndMsg {
        WndMsg {
            msg_id: winsafe::co::WM::SETTEXT,
            wparam: 0,
            lparam: "invalid".as_ptr() as isize + 0x10000,
        }
    }
}
```

```rust
wnd.hwnd().SendMessage(UnsoundMessageExample)
```

Exact offsets may cause mere text corruption, outright failure, or success.  Convincing windows to use the pointer to properly crash the program is suprisingly annoying - I wonder if the default window controls use IsBadXxxPtr ([which should be called CrashProgramRandomly](https://devblogs.microsoft.com/oldnewthing/20060927-07/?p=29563)).

PostThreadMessage also returns immediately before the recieving thread has a chance to handle the message, even though several MsgSend implementations own values (which get dropped) or have references (to things which could *be* dropped now that MsgSend no longer extends their lifetime).

**Comment by MaulingMonkey** [comment]
(I'm also unable to reopen this issue.)

**Comment by MaulingMonkey** [comment]
It *might* be sufficient to:
1. make MsgSend an `unsafe trait`
2. make PostThreadMessage require `MsgSend + Send + Copy + 'static`.
    * Without `Copy`, messages could `Drop` data on the sending thread before the recieving thread can access the message
    * Without `Send`, messages could contain references to `!Sync` such as `RefCell<T>` or `Rc<T>` that isn't thread safe to read
    * Without `'static`, messages could contain references to things that go out of scope before the message is processed

**Comment by rodrigocfd** [comment]
Those are great ideas. In particular, I forgot we can have an [unsafe trait](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html#implementing-an-unsafe-trait), which fits this situation perfectly.

Regarding `PostThreadMessage`, I believe the same ideas apply to [`PostMessage`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-postmessagew) (maybe with the exception of the `Copy` trait), since it also returns immediately. What do you think?

**Comment by MaulingMonkey** [comment]
Yes, I believe all the concerns of PostThreadMessage also 100% apply to PostMessage.
Also to SendMessage**Callback** and Send**Notify**Message, since they can return before the message is processed.

DispatchMessage, SendMessage, and SendMessage**Timeout** are a bit more relaxed: they at least wait for the message to be processed - even across threads - before returning/dropping.  ("Processed" here for Send\* might not mean the wndproc has returned, but it has at least called ReplyMessage, and thus "should" be done with the pointers...?).  But they should perhaps still require `Sync`?  Although, in practice, a message containing e.g. a `Rc<String>` is likely only passing the string pointer to the actual wndproc, not exposing thread-unsafe refcount mutation...

**Comment by rodrigocfd** [comment]
I really appreciated your feedback, thank you.
