### ISSUE TITLE
CreateWindowEx is unsound

### ISSUE THREAD

**Issue by MaulingMonkey** [rodrigocfd/winsafe#25]
lpParam needs to be a valid pointer in some cases:

> If an application calls [CreateWindow](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-createwindowa) to create a MDI client window, lpParam should point to a [CLIENTCREATESTRUCT](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-clientcreatestruct) structure. If an MDI client window calls CreateWindow to create an MDI child window, lpParam should point to a [MDICREATESTRUCT](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-mdicreatestructa) structure. lpParam may be NULL if no additional data is needed.
> <https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowexw>

However, `CreateWindowEx` is not `unsafe`, performs no relevant parameter validation, and makes lparam a simple to misconstruct `Option<isize>`.

https://github.com/rodrigocfd/winsafe/blob/04769f746af22c7e32985f97b09b5e064ac7c1fb/src/user/handles/hwnd.rs#L123-L135

**Comment by rodrigocfd** [comment]
You are correct, `CreateWindowEx` must be marked as `unsafe`.
