### ISSUE TITLE
winsafe::MSG doesn't match layout of windows.h MSG on 32-bit

### ISSUE THREAD

**Issue by MaulingMonkey** [rodrigocfd/winsafe#26]
The lpPrivate field at the end here:

https://github.com/rodrigocfd/winsafe/blob/6540aea9f58a058f5817743a420c68ab181b1925/src/user/structs.rs#L433-L443

Is only defined by windows.h if `_MAC` (macos / OS X) is defined:

```cpp
typedef struct tagMSG {
    HWND        hwnd;
    UINT        message;
    WPARAM      wParam;
    LPARAM      lParam;
    DWORD       time;
    POINT       pt;
#ifdef _MAC
    DWORD       lPrivate;
#endif
} MSG, *PMSG, NEAR *NPMSG, FAR *LPMSG;
```

On 64-bit, there's some implicit padding there anyways.  That's a bit sketchy if MSG were ever to be combined with MaybeUninit, as lPrivate could end up being left uninitialized.

On 32-bit, this actually changes the struct size (winsafe::MSG is 32 bytes, windows.h MSG is 28 bytes.)

Perhaps use `#[cfg(target_os = "macos")]` ?

**Comment by rodrigocfd** [comment]
This is actually a leftover from the early days of this library, when I was still experimenting. It should have been removed.

Thank you.
