### ISSUE TITLE
HDC::GetDIBits

### ISSUE THREAD

**Issue by anenankhu** [rodrigocfd/winsafe#28]
Hi, I'm trying to get a screenshot using winsafe, but there's no [GetDIBits](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getdibits) function, can it be added?

With windows-rs it looks atrocious:

```rust
let mut bmi = BITMAPINFO {
    bmiHeader: BITMAPINFOHEADER {
        biSize: std::mem::size_of::<BITMAPINFOHEADER>() as u32,
        biWidth: bmp.bmWidth,
        biHeight: -bmp.bmHeight,
        biPlanes: 1,
        biBitCount: 32,
        biCompression: BI_RGB as u32,
        biSizeImage: 0,
        biXPelsPerMeter: 0,
        biYPelsPerMeter: 0,
        biClrUsed: 0,
        biClrImportant: 0,
    },
    bmiColors: [RGBQUAD {
        rgbBlue: 0,
        rgbGreen: 0,
        rgbRed: 0,
        rgbReserved: 0,
    }],
};

//let size: usize = (width * height) as usize * 4;
let size: usize = (((bmp.bmWidth * (bmi.bmiHeader.biBitCount as i32) + 31) / 32) * 4 * bmp.bmHeight) as usize;
let mut data: Vec<u8> = Vec::with_capacity(size);
unsafe { data.set_len(size) };

unsafe {
    GetDIBits(
        hdc_mem, hbmp, 0, height as u32, &mut data[0] as *mut u8 as *mut c_void,
        &mut bmi,
        DIB_RGB_COLORS,
    );
}
```

**Comment by rodrigocfd** [comment]
I also added a full example of taking a screenshot and saving to file at the [GetDIBits docs](https://rodrigocfd.github.io/winsafe/winsafe/prelude/trait.GdiHdc.html#method.GetDIBits).

This commit will be included in the next version, but you can specify WinSafe as a dependency [straight from GitHub](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) so you can use it right away.

Let me know if this worked for you.

**Comment by anenankhu** [comment]
Thanks! It worked.
