### ISSUE TITLE
Visibility of the DISPLAY_DEVICE::DeviceID members

### ISSUE THREAD

**Issue by michidk** [rodrigocfd/winsafe#34]
Is there a specific reason why the getter for `DeviceID` and `DeviceKey` was removed from the `DISPLAY_DEVICE` struct?
Seems like it happened here: https://github.com/rodrigocfd/winsafe/commit/806c57509e1d747e8a7e36b1ec22917616669332#diff-61500d78eb074804b61d228b17c595974dd7cd10099a3cf8874919aee6239750R427

**Comment by rodrigocfd** [comment]
Hmm, looks like a mistake.
