### ISSUE TITLE
[user] EnumDisplayDevices result

### ISSUE THREAD

**Issue by michidk** [rodrigocfd/winsafe#36]
The [EnumDisplayDevices](https://github.com/rodrigocfd/winsafe/blob/master/src/user/funcs.rs#L183) function returns a WinResult<bool>. I don't see where `Ok(true)` is ever set. It also seems like it is not required because we also return a result.

Also, the current example in the docs of that function is a bit weird. The function is supposed to be called until the first error because that means that we finished iterating over all displays:
```rust
if !is_finished {
```
will never be the case, because the `?` will return the error.

**Comment by rodrigocfd** [comment]
As far as I could investigate, the enumeration ends when `EnumDisplayDevices` returns zero **and** `GetLastError` returns `ERROR_PROC_NOT_FOUND`, therefore the foolproof implementation has to consider this. The check is necessary to rule out legitimate errors.

I changed the implementation to reflect this. Please let me know if this worked for you.

**Comment by michidk** [comment]
Wow that was quick :D. I am not too familiar with Windows error handling stuff, but if I try to adjust my code like mentioned in the example:
```rust
/// Returns a list of all displays.
pub fn discover_displays() -> Result<DisplaySet> {
    let mut result = Vec::<Display>::new();

    let mut dev_num: u32 = 0;
    let mut display_device = DISPLAY_DEVICE::default();

    loop {
        let has_more = EnumDisplayDevices(
            None,
            dev_num,
            &mut display_device,
            EDD::GET_DEVICE_INTERFACE_NAME,
        )?;

        if has_more {
            result.push(Display::from_winsafe(dev_num, &display_device)?);
            dev_num += 1;
        } else {
            break;
        }
    }

    Ok(DisplaySet { displays: result })
}
```

Then the fn returns early with the following Err: "[0x00cb 203] The system could not find the environment option that was entered.".

The following works fine:
```rust
        let has_more = EnumDisplayDevices(
		...
        ); // no `?`

        if has_more.is_ok() { // `is_ok()` instead
            result.push(Display::from_winsafe(dev_num, &display_device)?);
            dev_num += 1;
        } else {
            break;
        }
```

This might have to do with the fact that I have one display that is `active: false`?

**Comment by michidk** [comment]
When I run your code, I get an infinite loop, because `is_good` is always `true`.

**Comment by rodrigocfd** [comment]
Maybe I'll have to add a specific handling inside the implementation... how do you know the display is inactive?

**Comment by michidk** [comment]
I only have three displays attached to the four DisplayPort ports on my GPU (maybe the forth one is also some kind of virtual display output device).
This is how the API calls look in APIMonitor:
![image](https://user-images.githubusercontent.com/3979930/170056879-c95ec010-8ca2-4812-99bf-b4cc22806134.png)
While all other display have the active flag there, my forth monitor shows this flag:
![image](https://user-images.githubusercontent.com/3979930/170057092-71c86919-6c78-4205-aa5b-cca2eac88f81.png)

**Comment by rodrigocfd** [comment]
It's just a `for` iterating from 0 to 7... it can't be an infinite loop.

Are you running this code inside something else?

**Comment by michidk** [comment]
Agh sorry. Wanted to get back to you ASAP and got sloppy: I had another loop {} around this from code before. This code actually doesn't loop. Output is:
```
0 Ok true
1 Ok true
2 Ok true
3 Ok true
4 Err [0x00cb 203] The system could not find the environment option that was entered.

5 Err [0x00cb 203] The system could not find the environment option that was entered.

6 Err [0x00cb 203] The system could not find the environment option that was entered.

7 Err [0x00cb 203] The system could not find the environment option that was entered.
```

**Comment by rodrigocfd** [comment]
What about [this example in the docs](https://rodrigocfd.github.io/winsafe/winsafe/fn.EnumDisplayDevices.html)? Does it still loop?

**Comment by rodrigocfd** [comment]
This means that when the loop ends, `GetLastError` returns code `203`, which should be the stop condition.

However... on my computer, it returns code `127` instead. That's odd.

I'm on Windows 10 x64, what's yours?

**Comment by michidk** [comment]
Output now is:
```
0: \\.\DISPLAY1 - NVIDIA GeForce GTX 1080
1: \\.\DISPLAY2 - NVIDIA GeForce GTX 1080
2: \\.\DISPLAY3 - NVIDIA GeForce GTX 1080
3: \\.\DISPLAY4 - NVIDIA GeForce GTX 1080
```

So it works!

We could also handle 127 as well as 203 as codes for `Ok(false)`.
