### ISSUE TITLE
Load icon from file?

### ISSUE THREAD

**Issue by GirkovArpa** [rodrigocfd/winsafe#38]
```rust
let name: u16 = // ?
let h_icon = HINSTANCE::NULL.LoadImageIcon(name, 16, 16, LR::LOADFROMFILE);
```

Why is name a `u16`?  Shouldn't a filename string be accepted?  

I would like to change the window icon at runtime from a file that isn't included in the resources.

**Comment by rodrigocfd** [comment]
Actually it was more complicated than that... we also must consider the 3 OEM resource flags: `OBM`, `OIC` and `OCR`. This demanded 3 new specific enums to deal with the 3 possibilities: ID, string or OEM resource. Which gives us 9 different possibilities.

I made a quick test and it seems to be correct and working now. Please let me know if you need something else.

**Comment by GirkovArpa** [comment]
Works perfectly!

```rust
let h_icon = HINSTANCE::NULL
    .LoadImageIcon(
        IdOicStr::Str(WString::from_str(
            "C:\\Temp\\foo.ico",
        )),
        SIZE::new(16, 16),
        LR::LOADFROMFILE,
    )
    .unwrap();

let window = gui::WindowMain::new(gui::WindowMainOpts {
    class_icon: gui::Icon::Handle(h_icon),
    ..Default::default()
});
```
