### ISSUE TITLE
Null value for bind_ctx

### ISSUE THREAD

**Issue by Benassou** [rodrigocfd/winsafe#40]
Hey all

I'm trying to translate a piece of c++ code (https://stackoverflow.com/questions/59926644/listing-of-installed-apps-on-windows-10) to rust. In it the author uses the BindToHandler function. I found that method in this crate as well but the problem is that in the original c++ code they pass a nullptr for the bindcontext. Since the bind context parameter in the BindToHandler method is not an option I can't pass None like I did with SHCreateItemFromParsingName. What would be the equivalent here of passing a NULL value in c++?

kr

**Comment by rodrigocfd** [comment]
Indeed, the example shows that this function accepts null, even if the [official documentation](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishellitem-bindtohandler) doesn't say this. It seems that the documentation was just poorly written, so I'm implementing this.
