### ISSUE TITLE
Add support for IEnumShellItems

### ISSUE THREAD

**Issue by Benassou** [rodrigocfd/winsafe#41]
hi

I'm trying to use the BindToHandler method to iterate over objects in a folder. According to the examples I have found I should use the EnumItems BHID for that. But that constant requires the IEnumShellItems interface which I don't believe is supported in this library. I have attemtped to use IShellItemArray instead like so `let ish_arr = shi.BindToHandler::<IShellItemArray>(None, &BHID::EnumItems).unwrap();` but then I get a `No such interface supported`.

Is there an alternative to this or will this interface be supported in the near-future? 

Thanks!

**Comment by rodrigocfd** [comment]
Let me know if it worked for you.

**Comment by rodrigocfd** [comment]
It felt natural to implement an iterator for `IEnumShellItems`, so [here it is](https://rodrigocfd.github.io/winsafe/winsafe/prelude/trait.shell_IEnumShellItems.html#method.iter).

**Comment by Benassou** [comment]
Thanks that indeed seems to work.

FYI, I did end up going for windows-rs even though this library provides an easier and cleaner interface because I needed quite a few more features than are currently implemented.
