### ISSUE TITLE
set background color of a label

### ISSUE THREAD

**Issue by antsol20** [rodrigocfd/winsafe#43]
This is a great piece of work.
But how do you set the bk color of a label (or set the mode to transparent)?
An example would be very helpful. Thanks!

**Comment by rodrigocfd** [comment]
Does this help?

https://stackoverflow.com/a/4495814

**Comment by antsol20** [comment]
Hi thanks.

I'm expecting a SetBkColor method in gdi_HDC
https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-setbkcolor

But don't see one?

Thanks

**Comment by rodrigocfd** [comment]
Oh I somehow missed it, but [it's here now](https://rodrigocfd.github.io/winsafe/winsafe/prelude/trait.gdi_Hdc.html#method.SetBkColor).

It will be published soon in the next version, but you can use it right away by pointing your Cargo dependency to the GitHub repo:

* https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories
