### ISSUE TITLE
SS_CENTER flag on Label not working

### ISSUE THREAD

**Issue by GirkovArpa** [rodrigocfd/winsafe#5]
I created the resource file in Resource Hacker, and saved the label with the `SS_CENTER` flag:

![resource hacker screenshot](https://i.imgur.com/Bc1nuEM.png)

But in the program it's displayed as left-aligned:

![bug screenshot](https://i.imgur.com/MBsZ3N2.gif)

[Code](https://github.com/GirkovArpa/winsafe-7guis/blob/e94341665c2f89269fef172a00d8366c57ac6e0d/organisateur/src/my_window/my_modal.rs#L40):

```rust
myself.lbl.set_text(&myself.input_val.borrow()).unwrap();
````

**Comment by rodrigocfd** [comment]
By default, the `Label` control was always resizing itself to match the text, what made the `SS_CENTER` basically useless.

I changed this behavior now: the auto-resizing must be explicitly told by calling either `resize_to_text` or `set_text_and_resize` methods. And for non-dialog windows, the `Label` will automatically resize only if you don't specify the `size` option.

If this fix won't solve your problem, please reopen this issue.

**Comment by GirkovArpa** [comment]
This will be in version `0.0.3`?

**Comment by rodrigocfd** [comment]
It surely will.

If you can't wait, you can clone the repo and use it as a [local dependency](https://stackoverflow.com/a/33025972).
