### ISSUE TITLE
Reg{Create,Open}KeyTransacted should take transaction by reference

### ISSUE THREAD

**Issue by Hawk777** [rodrigocfd/winsafe#55]
Lots of things that take a handle take it by reference, since the commit that made handles non-`Copy` and non-`Clone`—for example, `SetParent` takes an `&HWND` as the new parent, not an `HWND`. `RegCreateKeyTransacted` and `RegOpenKeyTransacted` currently take the `HTRANSACTION` by value; it probably makes sense for them to take it by reference instead, to avoid ugly calls to `raw_copy` in user code.

**Comment by rodrigocfd** [comment]
Oops... my bad.
