### ISSUE TITLE
Incorrect message parameters for WM_CHAR and friends

### ISSUE THREAD

**Issue by Hawk777** [rodrigocfd/winsafe#57]
In commit 8335fe26b45aad8d42ebe4390a0a97ef57ef5d3c, you changed the `pub_struct_msg_char` macro to generate a `char_code` field of type `co::VK` rather than `u16`. That macros is used for lots of messages right now, but their `wParam`s aren’t all the same!

* `WM_CHAR` gives a character code.
* `WM_KEYDOWN` gives a virtual-key code.
* `WM_KEYUP` gives a virtual-key code.
* `WM_SYSCHAR` gives a character code.
* `WM_SYSDEADCHAR` gives a character code.
* `WM_SYSKEYDOWN` gives a virtual-key code.
* `WM_SYSKEYUP` gives a virtual-key code.

Only those that carry a virtual-key code should be of type `VK`. The ones that carry a character code are either UTF-16 code units if the window class was registered with `RegisterClassW` or `RegisterClassExW`, or code page characters if registered with `RegisterClassA` or `RegisterClassExA`. So they should go back to being of type `u16` (don’t use `char` since some sources claim that a non-BMP character could be delivered by two consecutive `WM_CHAR` messages each containing a surrogate, and a Rust `char` cannot contain a surrogate, so each message on its own would fail to decode; only later after reassembling both messages do you actually have a complete character).

**Comment by rodrigocfd** [comment]
Parameter name is also different now, to make it easier on the eye: `char_code` vs `vkey_code`.

* [`wm::Char`](https://rodrigocfd.github.io/winsafe/winsafe/msg/wm/struct.Char.html)
* [`wm::KeyDown`](https://rodrigocfd.github.io/winsafe/winsafe/msg/wm/struct.KeyDown.html)

(There are a bunch of others, though.)
