### ISSUE TITLE
GetDlgCtrlId fails if the child window’s ID is actually zero

### ISSUE THREAD

**Issue by Hawk777** [rodrigocfd/winsafe#58]
The wrapper for `GetDlgCtrlId` tries to distinguish between zero-as-success and zero-as-failure by calling `GetLastError`. However, it does not call `SetLastError(ERROR_SUCCESS)` before calling `GetDlgCtrlId`, which means if the last error code was non-successful on entry and the value is zero, a spurious error will be returned. The documentation is vague as to whether the last error code is cleared on success or not by the underlying Windows API call, but I encountered this personally and it is not, so you should probably do it in the wrapper.

**Comment by rodrigocfd** [comment]
This is indeed undocumented behavior, but I'll trust your experience.
