### ISSUE TITLE
Sending messages to unsupported controls

### ISSUE THREAD

**Issue by GirkovArpa** [rodrigocfd/winsafe#6]
For example, the `msctls_progress32` control does not seem to be supported yet.  Is there a way to send custom messages to unsupported controls created in `.resource` files, using this function?

https://github.com/rodrigocfd/winsafe/blob/82bcca0421f374e9de9e75634ec6b2862ec76557/src/handles/hwnd.rs#L973-L982

In this specific case, I'd like to send `PBM_SETSTEP` messages.

**Comment by rodrigocfd** [comment]
Exactly. This is the [SendMessage](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessagew) function of the Windows API. You can create unsupported controls with [CreateWindowEx](https://rodrigocfd.github.io/winsafe/winsafe/struct.HWND.html#method.CreateWindowEx) just like you would in C++, and then use SendMessage to communicate – it's like working with the original Win32, but in Rust.

Do note that I'm implementing the high-level wrapper to the progress bar, though. Soon this approach will be no longer necessary.
