### ISSUE TITLE
Feature request: GetSystemMetricsForDpi

### ISSUE THREAD

**Issue by Hawk777** [rodrigocfd/winsafe#60]
It’s a useful function to have around, as a more modern replacement for `GetSystemMetrics`.

**Comment by rodrigocfd** [comment]
It's very interesting (and annoying) how [GetSystemMetricsForDpi](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetricsfordpi) can rely on GetLastError, while [GetSystemMetrics](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics) cannot. At least according to the official documentation.

**Comment by Hawk777** [comment]
True… though the docs do say that `GetSystemMetrics` can fail, they just don’t say that you can `GetLastError` afterwards. Which is weird since a bunch of the metrics codes also have zero as a legitimate return value.
