### ISSUE TITLE
ListBox:: new() ListBoxOpts list_box_style field ignores co::WS::HSCROLL flag when present 

### ISSUE THREAD

**Issue by jerrywrice** [rodrigocfd/winsafe#64]
I have a modified version of the Resizable_Layout example project source files which demonstrates the issue. Here's the window's widget support file contents =>

//
// Begin source file 'my_window.rs' *********************************************************
//
use winsafe::{prelude::*, self as w, gui, co};
use std::cell::Cell;
use winsafe::msg::lb::SetCurSel;
use winsafe::gui::Label;

#[derive(Clone)]
pub struct MyWindow {
	wnd: gui::WindowMain,
	lst: gui::ListBox,
	indexed_item_btn: gui::Button,
	list_index : Cell<u32>,
	_txt_label : Label,
	txt: gui::Edit,
	text_item_btn: gui::Button,
}

impl MyWindow {
	pub fn new() -> Self {
		let list_index = Cell::new(0u32);
		let wnd = gui::WindowMain::new(
			gui::WindowMainOpts {
				title: "Resizable layout".to_owned(),
				class_icon: gui::Icon::Id(101),
				size: (350, 500),
				style: gui::WindowMainOpts::default().style |
					co::WS::MINIMIZEBOX | co::WS::MAXIMIZEBOX | co::WS::SIZEBOX, // window can be resized
				..Default::default()
			},
		);

		// let enummask : co::LBS = (co::LBS::NOTIFY | co::LBS::from(u32::from(co::WS::BORDER))  | co::LBS::from(u32::from(co::WS::HSCROLL)) /*  | co::LBS::from(u32::from(co::WS::VSCROLL)) */ );
		// let bitmask : u32 = enummask.into();
		
		let lst = gui::ListBox::new(
			&wnd,
			gui::ListBoxOpts {
				list_box_style : (co::LBS::NOTIFY | co::LBS::from(u32::from(co::WS::BORDER)) | co::LBS::from(u32::from(co::WS::HSCROLL)) | co::LBS::from(u32::from(co::WS::VSCROLL))),
				position: (10, 10),
			// size: (280, 100),
				size: (180, 435),
				horz_resize: gui::Horz::Resize,  // resize horizontally with parent
				vert_resize: gui::Vert::Resize,  // resize veritcally with parent
				..Default::default()
			},
		);

		let indexed_item_btn = gui::Button::new(
			&wnd,
			gui::ButtonOpts {
				text: "&Add Indexed Item".to_owned(),
				position: (195, 410),
				width : 100,
				horz_resize: gui::Horz::Repos, // resize horizontally with parent
				vert_resize: gui::Vert::Repos, // move anchored at parent bottom
				..Default::default()
			},
		);

		let _txt_label = gui::Label::new(
            &wnd,
			gui::LabelOpts { 
              text : { "Enter Item text + click Apply".to_string() },
			  position: (10, 445),
			  horz_resize: gui::Horz::Resize, // resize horizontally with parent
			  vert_resize: gui::Vert::Repos,  // move anchored at parent bottom
			  size: (200, 20),
			  ..Default::default()
			},
		);

		let txt = gui::Edit::new(
			&wnd, 
			gui::EditOpts {
				position: (10, 465),
				width: 180,
				horz_resize: gui::Horz::Resize, // resize horizontally with parent
				vert_resize: gui::Vert::Repos,  // move anchored at parent bottom
				..Default::default()
			},
		);

		let text_item_btn = gui::Button::new(
			&wnd,
			gui::ButtonOpts {
				text: "&Add Text Item".to_owned(),
				position: (195, 465),
				width : 100,
				horz_resize: gui::Horz::Repos, // resize horizontally with parent
				vert_resize: gui::Vert::Repos, // move anchored at parent bottom
				..Default::default()
			},
		);

		let new_self = Self { wnd, lst, indexed_item_btn, _txt_label, txt, text_item_btn, list_index };

		new_self.events();
		
		new_self
	}

	pub fn run(&self) -> w::AnyResult<i32> {
		self.wnd.run_main(None)
	}

	fn events(&self) {
		
		{
		let self2 = self.clone();
		self.indexed_item_btn.on().bn_clicked(move || { // button click event
			// self2.wnd.hwnd().SetWindowText("Hello, world!")?;
            self2.list_index.set(self2.list_index.get() + 1u32);
			let a: String = "Item ".to_string() + &self2.list_index.get().to_string();
			let a_slice: &str = &a[..];  // take a full slice of the string
			let result = [a_slice];
			self2.lst.items().add(&result);
            let hi_item_index: u32 = self2.lst.items().count() - 1;
			let _x = self2.lst.hwnd().SendMessage( SetCurSel { index: Option::Some(hi_item_index) } ).unwrap(); // Move cursor to newest item in listbox
            Ok(())
		});
	    }
			
		{
		let self3 = self.clone();
			self.text_item_btn.on().bn_clicked(move || { // button click event
			    let current_user_text =	self3.txt.text();
				let current_user_text_slice: &str = &current_user_text[..];  // take a full slice of the string
				if current_user_text_slice.len() == 0 {
				   return Ok(());
				}
				let result = [current_user_text_slice];
				self3.lst.items().add(&result);
				let hi_item_index: u32 = self3.lst.items().count() - 1;
				let _x = self3.lst.hwnd().SendMessage( SetCurSel { index: Option::Some(hi_item_index) } ).unwrap(); // Move cursor to newest item in listbox
			    Ok(())
		});
	    }

	}
}
//
// End of source file 'my_window.rs' *********************************************************
//

Here is the main.rs file contents =>

//
// Begin source file 'main.rs' *********************************************************
//

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod my_window;

use winsafe::{prelude::*, self as w};
use my_window::MyWindow;

fn main() {
	if let Err(e) = run_app() {
		w::task_dlg::error(
			&w::HWND::NULL, "Unhandled error", None, &e.to_string())
			.unwrap();
	}
}

fn run_app() -> w::AnyResult<i32> {
	MyWindow::new()
		.run()
		.map_err(|err| err.into())
}

//
// End of source file 'main.rs' *********************************************************
//

**Comment by jerrywrice** [comment]
The ListBox list_box_style co::WS::HSCROLL flag does not result in the ListBox displaying the horizonal scroll bar whenever a list text item is wider than the displayed list box. The co::WS::VSCROLL flag works as expected. The following source snippet shows an instance of a ListBox which exhibits this issue.

		let lst = gui::ListBox::new(
 			          &wnd,
			          gui::ListBoxOpts {
				  list_box_style : (co::LBS::NOTIFY | co::LBS::from(u32::from(co::WS::BORDER)) | 
                                                           co::LBS::from(u32::from(co::WS::HSCROLL)) | co::LBS::from(u32::from(co::WS::VSCROLL))),
				  position: (10, 10),
				 size: (180, 435),
				 horz_resize: gui::Horz::Resize,  // resize horizontally with parent
				 vert_resize: gui::Vert::Resize,  // resize vertically with parent
				..Default::default()
			},
		);

**Comment by rodrigocfd** [comment]
This behavior has nothing to do with WinSafe.

In order to have proper horizontal scrolling on a ListBox control, you must send a [`LB_SETHORIZONTALEXTENT`](https://docs.rs/winsafe/latest/winsafe/msg/lb/struct.SetHorizontalExtent.html) message in addition to the `WS_HSCROLL` style. To get the width you need, call [`GetTextExtentPoint32`](https://docs.rs/winsafe/latest/winsafe/prelude/trait.gdi_Hdc.html#method.GetTextExtentPoint32) on the longest text you have on the list.

The ListBox is a very primitive control, with lots of weird behaviors. Consider using the ListView, which is its modern replacement.

**Comment by jerrywrice** [comment]
Thanks for the clarification and explanation. I'll convert and use the ListView control instead.
