### ISSUE TITLE
code panics on adding root to treeview

### ISSUE THREAD

**Issue by HJX-001** [rodrigocfd/winsafe#68]
**code**
```
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use winsafe::{prelude::*, gui, co, AnyResult, HWND};

#[derive(Clone)]
pub struct MyWindow {
	wnd:       gui::WindowMain,
	tv: gui::TreeView,
}

impl MyWindow {
	pub fn new() -> Self {
		let wnd = gui::WindowMain::new(
			gui::WindowMainOpts {
				title: "My window title".to_owned(),
				size: (300, 150),
				..Default::default()
			},
		);

		let tv = gui::TreeView::new(
			&wnd,
			Default::default(),
		);
		tv.items().add_root("text", None);

		let new_self = Self { wnd, tv };
		new_self
	}

	pub fn run(&self) -> AnyResult<i32> {
		self.wnd.run_main(None)
	}
}


fn main() {
	if let Err(e) = run_app() {
		HWND::NULL.MessageBox(
			&e.to_string(), "Uncaught error", co::MB::ICONERROR).unwrap();
	}
}

fn run_app() -> AnyResult<i32> {
	MyWindow::new()
		.run()
		.map_err(|err| err.into())
}
```

**error while compiling**
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: [0x00a0 160] One or more arguments 
are not correct.                                                                                           
', C:\Users\CP\\.cargo\registry\src\github.com-1ecc6299db9ec823\winsafe-0.0.13\src\gui\native_controls\tree_view_items.rs:44:14                                                                                        
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                              
error: process didn't exit successfully: `D:\Projects\temp\target\debug\temp.exe` (exit code: 101)

**system**
windows 10 x64

**Comment by rodrigocfd** [comment]
The problem is that you adding a node to the treeview control, but the control doesn't physically exist yet. That is: the treeview object has been created, but the owner window didn't render it yet.

In order to perform this operation, you must do it in the [`WM_CREATE`](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-create) event (if an ordinary window), or in the [`WM_INITDIALOG`](https://learn.microsoft.com/en-us/windows/win32/dlgbox/wm-initdialog) event (if a dialog window).

The example below shows you code, corrected:

```rust
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use winsafe::{prelude::*, gui, co, AnyResult, HWND};

#[derive(Clone)]
pub struct MyWindow {
	wnd:       gui::WindowMain,
	tv: gui::TreeView,
}

impl MyWindow {
	pub fn new() -> Self {
		let wnd = gui::WindowMain::new(
			gui::WindowMainOpts {
				title: "My window title".to_owned(),
				size: (300, 150),
				..Default::default()
			},
		);

		let tv = gui::TreeView::new(
			&wnd,
			Default::default(),
		);
		// tv.items().add_root("text", None); THIS LINE GOES TO WM_CREATE

		let new_self = Self { wnd, tv };
		new_self.events(); // add the window event handlers
		new_self
	}

	pub fn run(&self) -> AnyResult<i32> {
		self.wnd.run_main(None)
	}

	fn events(&self) {
		let self2 = self.clone();
		self.wnd.on().wm_create(move |_| { // called right after the window is created
			self2.tv.items().add_root("text", None);
			Ok(0)
		});
	}
}


fn main() {
	if let Err(e) = run_app() {
		HWND::NULL.MessageBox(
			&e.to_string(), "Uncaught error", co::MB::ICONERROR).unwrap();
	}
}

fn run_app() -> AnyResult<i32> {
	MyWindow::new()
		.run()
		.map_err(|err| err.into())
}
```

The message error doesn't help, though. I'll implement a better error handling for such case.
