### ISSUE TITLE
How to close a process?

### ISSUE THREAD

**Issue by DaZiYuan** [rodrigocfd/winsafe#72]
```rust
        let pi = HPROCESS::CreateProcess(
            None,
            Some("notepad.exe"),
            None,
            None,
            false,
            co::CREATE::NoValue,
            None,
            None,
            &mut startInfo,
        )
        .unwrap();

//       I want to close it programmatically
//        pi.hProcess.CloseHandle().unwrap(); 
```

**Comment by DaZiYuan** [comment]
I also want to know how to convert pi.hProcess to HWND. I would be grateful if you could help.

**Comment by DaZiYuan** [comment]
I tried this, but the notepad.exe didn't close successfully.
```rust
use winsafe::{self as w, prelude::*, co};
	
let mut si = w::STARTUPINFO::default();
let pp = w::HPROCESS::CreateProcess(None, Some("notepad.exe"), None,
	None, false, co::CREATE::NoValue, None, None, &mut si).unwrap();

// get copies of the handles

let hprocess = unsafe { pp.hProcess.raw_copy() };
let hthread = unsafe { pp.hThread.raw_copy() };

// prevent the drop of the struct

std::mem::forget(pp);

// manually release the handles

unsafe {
	let _ = w::guard::CloseHandleGuard::new(hprocess);
	let _ = w::guard::CloseHandleGuard::new(hthread);
}
```

> I've never seen this conversion before: what's the situation where it's needed?

I want to create a new Notepad process and obtain its main handle. Then, I want to convert the handle to an HWND to use the SetParent() function.

**Comment by DaZiYuan** [comment]
I made a mistake, the result of CreateProcess is not a window handle. However, I am still curious about how to manually kill the process

**Comment by rodrigocfd** [comment]
> I made a mistake, the result of CreateProcess is not a window handle.

Indeed, process and window are two completely different things. You cannot forcibly cast one handle into the other.

> However, I am still curious about how to manually kill the process

I think you're after [`TerminateProcess`](https://rodrigocfd.github.io/winsafe/winsafe/prelude/trait.kernel_Hprocess.html#method.TerminateProcess).

**Comment by DaZiYuan** [comment]
It looks great, I hope to use it soon.

**Comment by DaZiYuan** [comment]
works well in 0.0.15
