### ISSUE TITLE
How to pass a RECT as a parameter in MapWindowPoints?

### ISSUE THREAD

**Issue by DaZiYuan** [rodrigocfd/winsafe#73]
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapwindowpoints

> A pointer to an array of [POINT](https://learn.microsoft.com/en-us/windows/win32/api/windef/ns-windef-point) structures that contain the set of points to be converted. The points are in device units. This parameter can also point to a [RECT](https://learn.microsoft.com/en-us/windows/desktop/api/windef/ns-windef-rect) structure, in which case the cPoints parameter should be set to 2.

```rust
	/// [`MapWindowPoints`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapwindowpoints)
	/// method.
	fn MapWindowPoints(&self,
		hdest: &HWND, points: &mut [POINT]) -> SysResult<(i16, i16)>
	{
		SetLastError(co::ERROR::SUCCESS);
		match unsafe {
			user::ffi::MapWindowPoints(
				self.as_ptr(),
				hdest.as_ptr(),
				points.as_mut_ptr() as _,
				points.len() as _,
			)
		} {
			0 => Err(GetLastError()),
			n => Ok((LOWORD(n as _) as _, HIWORD(n as _) as _)),
		}
	}
```
Seems that the current code only supports POINT.

**Comment by rodrigocfd** [comment]
Does this new [`MapWindowPoints`](https://rodrigocfd.github.io/winsafe/winsafe/prelude/trait.user_Hwnd.html#method.MapWindowPoints) work for you?

**Comment by DaZiYuan** [comment]
Looks good

**Comment by DaZiYuan** [comment]
I'm sorry for the late reply. I just realized that Rust can directly reference a Git repository. I have tested it and it works fine.
