### ISSUE TITLE
Add `GetVolumePathName` function

### ISSUE THREAD

**Issue by GreenYun** [rodrigocfd/winsafe#78]
In order to gracefully call [`windafe::GetVolumeInformation`](https://docs.rs/winsafe/latest/winsafe/fn.GetVolumeInformation.html#), we should pass some `root_path_name` to the function, which are acquired via [`GetVolumePathNameW`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getvolumepathnamew).

Also, [`GetDiskSpaceInformationW`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getdiskspaceinformationw) is useful to retrieve some disk space information like available space and sector size.

**Comment by rodrigocfd** [comment]
Let me know if the functions work for you.
