### ISSUE TITLE
Wrong GetAsyncKeyState return type.

### ISSUE THREAD

**Issue by makindotcc** [rodrigocfd/winsafe#82]
Hi. [GetAsyncKeyState](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getasynckeystate) should return some kind of enum maybe rather than bool (https://github.com/rodrigocfd/winsafe/blob/e1918fde3dec27d1386e9a2e7c22b52877b2499c/src/user/funcs.rs#L399-L401). GetAsyncKeyState returns multiple key states: hold, was pressed after previous call to GetAsyncKeyState ("However, you should not rely on this last behavior" so I don't know if this is actually important in "safe" crate, if not then most significant bit should be checked instead rather than comparing it with 0).

**Comment by rodrigocfd** [comment]
> GetAsyncKeyState returns multiple key states: hold, was pressed after previous call to GetAsyncKeyState ("However, you should not rely on this last behavior" so I don't know if this is actually important in "safe" crate

I'd say this is important not only in the context of a safe crate: even in C++ code we shouldn't rely on that.

> then most significant bit should be checked instead rather than comparing it with 0

You are correct. I fixed the implementation with example given in the [documentation itself](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getasynckeystate).

**Comment by makindotcc** [comment]
I think it should be ``& 0x8000 != 0`` or just ``< 0`` (since its the sign bit), because with current version it will return true even if key is not held anymore (but was held in previous GetAsyncKeyState call):
```rs
use std::thread::sleep;
use std::time::Duration;
use winapi::um::winuser::{GetAsyncKeyState, VK_CONTROL};

fn main() {
    println!("Hello, world!");
    loop {
        sleep(Duration::from_secs(5));
        println!("state: {:?}", unsafe { GetAsyncKeyState(VK_CONTROL) & 0x01 });
    }
}
```

**Comment by rodrigocfd** [comment]
Yep, that's it.

Can you check now?

**Comment by makindotcc** [comment]
It's working :) thank you, this crate saves so much pain.
