### ISSUE TITLE
SetLayeredWindowAttributes

### ISSUE THREAD

**Issue by henryrgithub** [rodrigocfd/winsafe#83]
Is there support for this function that I'm not seeing? I'll probably work on a PR if there isn't, I just want to make sure that I'm not duplicating work.

**Comment by rodrigocfd** [comment]
It was missing. Let me know if this works for you.

**Comment by henryrgithub** [comment]
Thanks for the fast turnaround! I'm still poking around and trying to get it to work how I want to, but I am at least getting it to return an invalid handle error ;) I'm sure it'll work great once I start using it right.

**Comment by henryrgithub** [comment]
Works great, thanks again!
