### ISSUE TITLE
How to display rich text such as superscript/subscript?

### ISSUE THREAD

**Issue by lotuslakestudio** [rodrigocfd/winsafe#86]
As title.

**Comment by rodrigocfd** [comment]
Where, exactly?

**Comment by lotuslakestudio** [comment]
In a label, a line edit box as well.

**Comment by rodrigocfd** [comment]
There is no native support for superscript/subscript, but I can imagine two possible implementations:

1. For static labels, you can have 2 different labels, where the 2nd has a smaller font and is positioned above. Each time you set the text, you manually set the text and width of both;

2. For static labels and edit controls, creating a [custom control](https://github.com/rodrigocfd/winsafe-examples/tree/master/04_custom_control) so you can manually render anything you want.

Personally, I've never seen an implementation of superscript/subscript.
