### ISSUE TITLE
[Feature Request] Message only window support

### ISSUE THREAD

**Issue by ClSlaid** [rodrigocfd/winsafe#89]
> Message-Only Windows
>
> A message-only window enables you to send and receive messages. It is not visible, has no z-order, cannot be enumerated, and does not receive broadcast messages. The window simply dispatches messages.
> 
> To create a message-only window, specify the [HWND_MESSAGE](https://learn.microsoft.com/en-us/windows/win32/winmsg/window-features?redirectedfrom=MSDN#message-only-windows) constant or a handle to an existing message-only window in the hWndParent parameter of the [CreateWindowEx](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowexa) function. You can also change an existing window to a message-only window by specifying HWND_MESSAGE in the hWndNewParent parameter of the [SetParent](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setparent) function.
> 
> To find message-only windows, specify [HWND_MESSAGE](https://learn.microsoft.com/en-us/windows/win32/winmsg/window-features?redirectedfrom=MSDN#message-only-windows) in the hwndParent parameter of the [FindWindowEx](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-findwindowexa) function. In addition, FindWindowEx searches message-only windows as well as top-level windows if both the hwndParent and hwndChildAfter parameters are NULL.
-- https://learn.microsoft.com/en-us/windows/win32/winmsg/window-features?redirectedfrom=MSDN#message-only-windows

Windows offers a way to create invisible and message only windows. By setting the `hWndParent` to `HWND_MESSAGE` in `CreateWindowEx`, you will get a message only window.

The reason why I request this feature here is that I miss your "on events()" idiom pretty much and don't want to manually deal with `lpfnWndProc`.

**Comment by rodrigocfd** [comment]
I'm aware of the existence of message-only windows, and I somehow get the concept. But personally I never used one, and I never felt the need to use one. That's why I didn't implement one – I don't know what they are for.

So, in order to write a proper implementation, I must ask: what's your specific use case?

**Comment by rodrigocfd** [comment]
I wrote a preliminar implementation of [`WindowMessageOnly`](https://rodrigocfd.github.io/winsafe/winsafe/gui/struct.WindowMessageOnly.html), but I have no idea how to test it.

Does it solve your problem?
