### ISSUE TITLE
WM_MENUSELECT

### ISSUE THREAD

**Issue by GirkovArpa** [rodrigocfd/winsafe#9]
I can listen for menu list open events.  But what about for when a specific menu item is clicked?  I dont see [WM_MENUSELECT](https://docs.microsoft.com/en-us/windows/win32/menurc/wm-menuselect) in the documentation.

My menu is created in a resource file, if it matters.

![screenshot](https://i.imgur.com/mIordRW.gif)

**Comment by GirkovArpa** [comment]
I think I can do it following the example [here](https://rodrigocfd.github.io/winsafe/winsafe/gui/events/struct.WindowEvents.html) using a custom event.

**Comment by GirkovArpa** [comment]
I'm trying to determine if a `MENUSELECT` event is generated by the user clicking a menu item.  I would expect `flags & MOUSESELECT` to be either `0` or `1` depending on whether it was a click or not, but it's always `32768`.

A picture says a thousand words, right?

I can't tell if the user clicked or just hovered a menu item.  Am I doing something wrong?

![screenshot](https://i.imgur.com/Y3amHFJ.gif)

**Comment by GirkovArpa** [comment]
Solved [here](https://stackoverflow.com/a/66965039/13378247) on stackoverflow.

**Comment by rodrigocfd** [comment]
> Solved [here](https://stackoverflow.com/a/66965039/13378247) on stackoverflow.

Awesome. That's exactly what I wanted to happen: common Win32 knowledge being used with WinSafe.

Just for the record, [WM_MENUCOMMAND](https://rodrigocfd.github.io/winsafe/winsafe/gui/events/struct.WindowEvents.html#method.wm_menu_command) event is available now:

```rust
self.wnd.on().wm_menu_command(move |params| {
    println("{}", params.item_index);
});
```
