### ISSUE TITLE
Build fails for the i686-pc-windows-(msvc/gnu) targets

### ISSUE THREAD

**Issue by Refragg** [rodrigocfd/winsafe#98]
Hello, I've been trying to use this library's CommandLineToArgvW and it seems like it builds correctly on all 64 bits architectures but it fails to build on i686-pc-windows both MSVC and GNU.
Here's what I'm getting when running `cargo build --target i686-pc-windows-gnu`:
```rust
error[E0599]: no method named `as_ptr` found for reference `&Self` in the current scope
   --> /home/refrag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winsafe-0.0.17/src/user/handles/hwnd.rs:766:43
    |
766 |         unsafe { user::ffi::GetWindowLongW(self.as_ptr(), index.raw()) }
    |                                                 ^^^^^^ help: there is a method with a similar name: `ptr`

error[E0599]: no method named `as_ptr` found for reference `&Self` in the current scope
    --> /home/refrag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winsafe-0.0.17/src/user/handles/hwnd.rs:1646:43
     |
1646 |         unsafe { user::ffi::SetWindowLongW(self.as_ptr(), index.raw(), new_long) }
     |                                                 ^^^^^^ help: there is a method with a similar name: `ptr`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `winsafe` (lib) due to 2 previous errors
```

Here's how it's imported in the project:
`winsafe = { version = "0.0.17", features = ["shell"], default-features = false }`

I'm down to provide more details if needed, hope you have a nice day.

**Comment by rodrigocfd** [comment]
Hi,

Very strange error. Please try using the latest version, [straight from the repo](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories):

```toml
[dependencies]
winsafe = { git = "https://github.com/rodrigocfd/winsafe", features = [] }
```

And see if you have any success.

**Comment by Refragg** [comment]
Just tried it now, it is the exact same from the repository unfortunately.

**Comment by rodrigocfd** [comment]
Can you post the source code which is triggering this error, please?

**Comment by Refragg** [comment]
Sure, it is [in this repo](https://github.com/Refragg/obs-livesplit-one) and more specifically here https://github.com/Refragg/obs-livesplit-one/blob/88dd5c751e93db9e506fb2bc7ca959835112d5d7/src/lib.rs#L739-L747

**Comment by rodrigocfd** [comment]
This is very odd. You're calling `CommandLineToArgv`, but the compilation error happens in `GetWindowLong`, which is completely unrelated.

Could you test the following simple program, and see what happens?

```rust
fn main() {
	match winsafe::CommandLineToArgv("a b c") {
		Ok(a) => println!("{:?}", a),
		Err(e) => println!("{:?}", e),
	}
}
```

**Comment by Refragg** [comment]
The same error appears at compile time with this simple example

**Comment by rodrigocfd** [comment]
In the end, it was just a minor syntax error: the handle method is called `ptr()`, not `as_ptr()`.

Let me know if this works.

**Comment by Refragg** [comment]
Seems like it does fix it! Thank you for the quick fix!
